### PR TITLE
Allow taking serial device from command line

### PR DESCRIPTION
**Pull request by baruch**
I usually have several usb to serial devices connected and need a way to tell the application what port to use.

### CODE REVIEW

**Comment by jlhonora** [comment]
Hi Baruch, thanks for your contribution. Just some slight modifications:

```
diff --git a/mastech.py b/mastech.py
index d052871..8063d2d 100755
--- a/mastech.py
+++ b/mastech.py
@@ -23,12 +23,12 @@ from bitarray import bitarray
 # works in Linux and Mac, should be modified
 # for Windows use
 def get_serial_port_name():
-   names = glob.glob('/dev/ttyusb*') + glob.glob('/dev/ttyUSB*')
+   names = glob.glob('/dev/tty.usb*') + glob.glob('/dev/ttyUSB*')
    if len(names) == 0:
        print 'No serial port found!'
        sys.exit(1)
    elif len(names) > 1:
-       print 'More than one serial port found: ',
+       print "%d serial ports found: " % len(names),
        for name in names:
            print name,
        print
```

The `tty.usb` part is needed for OS X device naming. Change that and we're good to go :)

**Comment by baruch** [comment]
I'm fine with these changes.

**Comment by jlhonora** [comment]
Great, we have two options:
- You update the pull request accordingly
- Give me access to your fork and I'll update it there to then accept the PR

**Comment by baruch** [comment]
I would recommend simply taking the pull request and putting that change on top. Sounds easier overall. It will also preserve authorship correctly.

But if you want I'll add that patch on top of mine and update the pull request. No problem with that.

**Pull request merged**
